# Site wide configuration

title: N-Mac
locale: en_US
theme: jekyll-theme-minimal
include:
 - _posts

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: N-Mac
  avatar: n-mac_hiking.jpg
  bio: "Data practitioner"
  linkedin: #username
  github: n-mac
