# Site wide configuration

title: N-Mac
locale: en_US
theme: jekyll-theme-minimal
![Image]({{site.url}}/_images/n-mac_hiking.jpg)

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: N-Mac
  #avatar: bio-photo.jpg
  bio: "Data practitioner"
  linkedin: #username
  github: n-mac
